// server.js
// Backend Express server for the trading analysis application.

const express = require('express');
const WebSocket = require('ws');
const dotenv = require('dotenv');
const fetch = require('node-fetch');

// Load environment variables from .env file
dotenv.config();

const app = express();
const port = 3000;

// Middleware to parse JSON bodies
app.use(express.json());
// Serve static files from the 'public' directory
app.use(express.static('public'));

/**
 * Deriv API communication via WebSocket.
  * @param {string} asset - The financial asset to fetch data for (e.g., 'R_100').
   * @param {string} timeframe - The timeframe for the data (e.g., 'M1', 'H1').
    * @returns {Promise<any>} A promise that resolves with the fetched ticks data.
     */
     function getMarketData(asset, timeframe) {
         return new Promise((resolve, reject) => {
                 const ws = new WebSocket('wss://ws.binaryws.com/websockets/v3?app_id=1089');

                         ws.onopen = () => {
                                     ws.send(JSON.stringify({
                                                     "ticks_history": asset,
                                                                     "end": "latest",
                                                                                     "count": 10500,
                                                                                                     "style": "candles",
                                                                                                                     "granularity": getTimeframeInSeconds(timeframe)
                                                                                                                                 }));
                                                                                                                                         };

                                                                                                                                                 ws.onmessage = (msg) => {
                                                                                                                                                             const data = JSON.parse(msg.data);
                                                                                                                                                                         if (data.error) {
                                                                                                                                                                                         reject(data.error.message);
                                                                                                                                                                                                         ws.close();
                                                                                                                                                                                                                     } else if (data.msg_type === 'candles') {
                                                                                                                                                                                                                                     if (data.candles && data.candles.length > 0) {
                                                                                                                                                                                                                                                         resolve(data.candles);
                                                                                                                                                                                                                                                                         } else {
                                                                                                                                                                                                                                                                                             reject(`No candle data returned for asset ${asset} and timeframe.`);
                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                             ws.close();
                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                 };

                                                                                                                                                                                                                                                                                                                                                         ws.onclose = () => {};
                                                                                                                                                                                                                                                                                                                                                                 ws.onerror = (err) => {
                                                                                                                                                                                                                                                                                                                                                                             reject('WebSocket error: ' + err.message);
                                                                                                                                                                                                                                                                                                                                                                                     };
                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                         /**
                                                                                                                                                                                                                                                                                                                                                                                          * Converts human-readable timeframe to seconds for the Deriv API.
                                                                                                                                                                                                                                                                                                                                                                                           * @param {string} timeframe - The timeframe string (e.g., '1m', '5m', '1H').
                                                                                                                                                                                                                                                                                                                                                                                            * @returns {number} The timeframe in seconds.
                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                             function getTimeframeInSeconds(timeframe) {
                                                                                                                                                                                                                                                                                                                                                                                                 const unit = timeframe.slice(-1).toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                                     const value = parseInt(timeframe.slice(0, -1));
                                                                                                                                                                                                                                                                                                                                                                                                         switch (unit) {
                                                                                                                                                                                                                                                                                                                                                                                                                 case 'm': return value * 60;
                                                                                                                                                                                                                                                                                                                                                                                                                         case 'h': return value * 3600;
                                                                                                                                                                                                                                                                                                                                                                                                                                 default: return 60;
                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                     // API endpoint to analyze market data
                                                                                                                                                                                                                                                                                                                                                                                                                                     app.post('/api/analyze', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                         const { asset, timeframe } = req.body;

                                                                                                                                                                                                                                                                                                                                                                                                                                             if (!asset || !timeframe) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                     return res.status(400).json({ error: 'Asset and timeframe are required.' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                             try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const marketData = await getMarketData(asset, timeframe);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const prompt = `You are a financial market expert. Analyze the following trading data and return ONLY a JSON object with three keys: "entryPoint", "stopLoss", and "takeProfit". Do not include any other text or markdown formatting. Data: ${JSON.stringify(marketData)}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const apiKey = process.env.GEMINI_API_KEY;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${apiKey}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const aiResponse = await fetch(apiUrl, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         contents: [{ parts: [{ text: prompt }] }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!aiResponse.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const errorBody = await aiResponse.text();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             throw new Error(`Gemini API request failed with status ${aiResponse.status}: ${errorBody}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const aiResult = await aiResponse.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!aiResult.candidates || !aiResult.candidates[0].content.parts[0].text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  throw new Error('Invalid response structure from Gemini API.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const responseText = aiResult.candidates[0].content.parts[0].text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // *** FIX: More robust JSON parsing to handle imperfect AI responses. ***
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // This logic finds the first '{' and the last '}' in the response text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // extracts the content between them, and then parses it. This effectively
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // strips out any extra text or markdown formatting.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const jsonStartIndex = responseText.indexOf('{');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const jsonEndIndex = responseText.lastIndexOf('}');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (jsonStartIndex === -1 || jsonEndIndex === -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error("Could not find JSON object in response:", responseText);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          throw new Error('Could not find a valid JSON object in the AI response.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const jsonString = responseText.substring(jsonStartIndex, jsonEndIndex + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const analysis = JSON.parse(jsonString);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.json(analysis);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error("Final attempt to parse JSON failed. String was:", jsonString);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  throw new Error('Could not parse the JSON analysis from the AI response.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error('Analysis error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.status(500).json({ error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  app.listen(port, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`Server running at http://localhost:${port}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
